//! Claim-file format (v1) and the report model shared by `eval`, `report`,
//! `ci`, and `diff`. Serde-(de)serializable to both YAML and JSON.

use crate::enums::VerdictStatus;
use serde::{Deserialize, Serialize};

/// Severity of a claim, used by CI fail policy.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "lowercase")]
pub enum Severity {
    Info,
    #[default]
    Warning,
    Error,
}

impl Severity {
    pub fn as_str(&self) -> &'static str {
        match self {
            Severity::Info => "info",
            Severity::Warning => "warning",
            Severity::Error => "error",
        }
    }

    /// Rank for threshold comparison (info < warning < error).
    pub fn rank(&self) -> u8 {
        match self {
            Severity::Info => 0,
            Severity::Warning => 1,
            Severity::Error => 2,
        }
    }
}

/// Where a claim came from when generated by `truth claims`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ClaimSource {
    pub file: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub line: Option<u32>,
}

/// How a claim was extracted by `truth claims`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ClaimExtraction {
    /// "regex" | "llm" | "manual".
    pub method: String,
    pub confidence: f32,
}

/// File-level metadata.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct ClaimFileMetadata {
    #[serde(default)]
    pub name: Option<String>,
    #[serde(default)]
    pub description: Option<String>,
}

/// Defaults applied to every claim unless overridden.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct ClaimDefaults {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub repo: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub local_log: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub env: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub window: Option<String>,
}

/// One claim specification.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ClaimSpec {
    pub id: String,
    pub text: String,
    #[serde(default)]
    pub severity: Severity,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tags: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expected_status: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub repo: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub local_log: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub env: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub window: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source: Option<ClaimSource>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extraction: Option<ClaimExtraction>,
}

impl ClaimSpec {
    /// Effective repo, applying file defaults.
    pub fn repo<'a>(&'a self, defaults: &'a ClaimDefaults) -> Option<&'a str> {
        self.repo.as_deref().or(defaults.repo.as_deref())
    }
    pub fn local_log<'a>(&'a self, defaults: &'a ClaimDefaults) -> Option<&'a str> {
        self.local_log.as_deref().or(defaults.local_log.as_deref())
    }
}

fn default_version() -> u32 {
    1
}

/// The claim-file (v1) format that powers `report`/`ci` (and, via conversion,
/// `eval`).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ClaimFile {
    #[serde(default = "default_version")]
    pub version: u32,
    #[serde(default)]
    pub metadata: ClaimFileMetadata,
    #[serde(default)]
    pub defaults: ClaimDefaults,
    pub claims: Vec<ClaimSpec>,
}

impl ClaimFile {
    pub fn from_yaml(s: &str) -> Result<Self, serde_yaml::Error> {
        serde_yaml::from_str(s)
    }
    pub fn to_yaml(&self) -> Result<String, serde_yaml::Error> {
        serde_yaml::to_string(self)
    }
}

// ---------- report model ----------

/// A piece of cited evidence as rendered into a report.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RenderedEvidence {
    pub source: String,
    pub kind: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub citation: Option<String>,
}

/// Per-status counts.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ReportSummary {
    pub supported: usize,
    pub contradicted: usize,
    pub partially_supported: usize,
    pub inconclusive: usize,
    pub needs_more_context: usize,
}

impl ReportSummary {
    pub fn tally(&mut self, status: VerdictStatus) {
        match status {
            VerdictStatus::Supported => self.supported += 1,
            VerdictStatus::Contradicted => self.contradicted += 1,
            VerdictStatus::PartiallySupported => self.partially_supported += 1,
            VerdictStatus::Inconclusive => self.inconclusive += 1,
            VerdictStatus::NeedsMoreContext => self.needs_more_context += 1,
        }
    }
}

/// One claim's check result inside a report.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReportResult {
    pub id: String,
    pub text: String,
    pub severity: Severity,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tags: Vec<String>,
    pub status: String,
    pub confidence: f32,
    pub check_id: String,
    pub summary: String,
    pub evidence: Vec<RenderedEvidence>,
    pub caveats: Vec<String>,
}

/// The full report produced by `truth report`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Report {
    pub generated_at: String,
    pub claims_checked: usize,
    pub summary: ReportSummary,
    pub results: Vec<ReportResult>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_claims_v1() {
        let yaml = r#"
version: 1
metadata:
  name: sample
defaults:
  repo: .
  window: 7d
claims:
  - id: checkout-unused
    text: nobody uses /v1/checkout anymore
    severity: warning
    tags: [usage, checkout]
    expected_status: contradicted
  - id: service-port
    text: the service runs on port 8080
    severity: info
"#;
        let cf = ClaimFile::from_yaml(yaml).unwrap();
        assert_eq!(cf.version, 1);
        assert_eq!(cf.claims.len(), 2);
        assert_eq!(cf.claims[0].severity, Severity::Warning);
        assert_eq!(cf.claims[0].tags, vec!["usage", "checkout"]);
        assert_eq!(cf.defaults.window.as_deref(), Some("7d"));
        // Severity defaults to warning when omitted... but here info is set.
        assert_eq!(cf.claims[1].severity, Severity::Info);
    }

    #[test]
    fn severity_defaults_to_warning() {
        let yaml = "claims:\n  - id: a\n    text: the service runs on port 8080\n";
        let cf = ClaimFile::from_yaml(yaml).unwrap();
        assert_eq!(cf.claims[0].severity, Severity::Warning);
        assert_eq!(cf.version, 1);
    }

    #[test]
    fn round_trips_to_yaml() {
        let yaml =
            "claims:\n  - id: a\n    text: the service runs on port 8080\n    severity: info\n";
        let cf = ClaimFile::from_yaml(yaml).unwrap();
        let out = cf.to_yaml().unwrap();
        let reparsed = ClaimFile::from_yaml(&out).unwrap();
        assert_eq!(reparsed.claims[0].id, "a");
    }
}
